apps:
  - script   : ./server.js
    name     : 'node_example-app'
    instances: 1
    exec_mode: cluster
    watch: false
    env:
      NODE_ENV: development
    env_production:
      NODE_ENV: production
    env_staging:
      NODE_ENV: staging